FROM 10.112.159.88:40007/node:4.8

RUN 	useradd -u 1500 --create-home jenkins2 && umask 002 && mkdir -p workspace; 
WORKDIR /home/jenkins2

ADD 	http://nexus.sandbox.extranet.group/nexus/content/repositories/binaries/node-sass/v4.5.1/linux-x64-46_binding.node   linux-x64-46_binding.node

ENV 	SASS_BINARY_PATH=/home/jenkins2/linux-x64-46_binding.node \
		NVM_NODEJS_ORG_MIRROR=http://nexus.sandbox.extranet.group/nexus/content/sites/binaries/node \
		HTTP_PROXY=http://10.113.140.187:3128 \
		HTTPS_PROXY=http://10.113.140.187:3128 \
		http_proxy=http://10.113.140.187:3128 \
		https_proxy=http://10.113.140.187:3128 \
		no_proxy=localhost,127.0.0.1,sandbox.local,lbg.eu-gb.mybluemix.net,lbg.eu-gb.bluemix.net,10.113.140.170,10.113.140.179,10.113.140.187,10.113.140.168,jenkins.sandbox.extranet.group,nexus.sandbox.extranet.group,gerrit.sandbox.extranet.group,sonar.sandbox.extranet.group,extranet.group

RUN 	chown jenkins2:jenkins2  * -R && \
		npm config set registry http://nexus.sandbox.extranet.group/nexus/content/groups/npm-master/ && \
		npm install npm3 gulp yarn eslint -g && \
		npm cache clean && \
		rm -rf ~/.npm
		
USER 	jenkins2 
WORKDIR /home/jenkins2/workspace
